import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import { CartProvider } from "@/context/cartContext";
import { AuthProvider } from "@/context/authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nebula store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta property="og:title" content="Nebula store" />
        <meta property="og:description" content="E-commerce de tecnologia" />
        <meta property="og:image" content="/public/nebula3.png" />
        <meta
          property="og:url"
          content="https://pm4fsdeploy-9eca.vercel.app/"
        />
        <meta name="twitter:card" content="summary_large_image" />

        <link rel="icon" href="/icons/nebula.png" />
        <title>Nebula store</title>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
